// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Player, PlayerData } from "./tables/Player.sol";
import { Tree } from "./tables/Tree.sol";
